### ISSUE TITLE
seL4 Kernel 

### ISSUE THREAD

**Issue by chrisguikema** [seL4/sel4bench-manifest#1]
The seL4 Kernel Git project doesn't have a 4.0.x-compatible branch, so when pulling the code it fails immediately. 

"fatal: Couldn't find remote ref refs/heads/4.0.x-compatible"

Should be:
`<project name="seL4.git" path="kernel">
<linkfile src="libsel4" dest="libs/libsel4"/>
</project>`

**Comment by kent-mcleod** [comment]
I believe that this was fixed in 261f8c1125ae6dc7b787c534c0d7e7c40745966d.
