### ISSUE TITLE
CI test should execute at least a build

### ISSUE THREAD

**Issue by axel-h** [seL4/sel4bench-manifest#10]
It seems the github CI action do not build or test anything for PRs done here. There are some some simple check about the 
change set. While testing might require more work, running builds would be helpful to ensure this project is consistent.

**Comment by lsf37** [comment]
The sel4bench action is not done yet (seL4/ci-actions#75). The plan for it would be to run at least the compile part of it here, and the full set on sel4bench. Changes in repos that are mentioned in sel4bench-manifest will trigger a full test inside sel4bench.

**Comment by lsf37** [comment]
Coming up in seL4/ci-actions#162

**Comment by kent-mcleod** [comment]
Can this be closed @lsf37 ?

**Comment by lsf37** [comment]
I guess I should still add a workflow in the manifest repo, currently we're only triggering tests from the sel4bench repo and repos that sel4bench depends on.
