### ISSUE TITLE
Benchmark is not working for x86_64 with gcc 11

### ISSUE THREAD

**Issue by dinukaamarasinghe817** [seL4/sel4bench-manifest#16]
I successfully executed `init-build.sh` script with default arguments as mentioned in https://docs.sel4.systems/projects/sel4bench/status.html

```mkdir sel4bench
cd sel4bench
repo init -u https://github.com/seL4/sel4bench-manifest.git
repo sync
mkdir build
cd build
../init-build.sh
```

But when i execute `ninja` it gives me this output saying the build was not successful.

```
[76/258] Building C object apps/sel4bench/projects_libs/libjansson/CMakeFiles/jansson.dir/jansson-2.7/src/load.c.obj
...
<continue error message>
...
/home/dinuka/Research/sel4bench/projects/sel4bench/apps/sel4bench/src/ipc.c: In function ‘process_ipc_results’:
/home/dinuka/Research/sel4bench/projects/sel4bench/apps/sel4bench/src/ipc.c:40:27: internal compiler error: Segmentation fault
   40 |         overhead_result = process_result(RUNS - 1, raw_results->overhead_benchmarks[i], desc);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0x770a5644251f ???
	./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x770a56429d8f __libc_start_call_main
	../sysdeps/nptl/libc_start_call_main.h:58
0x770a56429e3f __libc_start_main_impl
	../csu/libc-start.c:392
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
ninja: build stopped: subcommand failed.
``` 

any idea why?

**Comment by lsf37** [comment]
Not sure if this will fix anything, but CI for x64 is running

```
mkdir build
cd build
../init-build.sh -DFASTPATH=TRUE -DHARDWARE=TRUE -DFAULT=TRUE -DPLATFORM=x86_64
ninja
```

That does at least seem to work for me locally as well.

Edit: just saw the `internal compiler error: Segmentation fault 40` in your log. That's pretty impressive. It look like this is gcc-11 which I would expect to work, but just to make sure, maybe try gcc-10, which is the officially supported version at the moment.

**Comment by dinukaamarasinghe817** [comment]
Yes you are right. it works without any error with gcc-10.

I have another question,
Is it possible to perform the benchmark with QEMU ? for x86_64 ?

**Comment by lsf37** [comment]
> Yes you are right. it works without any error with gcc-10.

Cool. I'll add an issue that gcc-11 is currently broken for sel4bench.
 
> I have another question, Is it possible to perform the benchmark with QEMU ? for x86_64 ?

It doesn't really make sense to run these benchmarks on an emulator, unfortunately. The timings would be completely off, and I'm not even sure you could compare two runs of the same emulator, because it would depend on what else the host machine is doing.

**Comment by lsf37** [comment]
I'll close this one here, but I've linked it from https://github.com/seL4/sel4bench/issues/49.
